services:
  wireguard-manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_SUPABASE_URL: ${PUBLIC_SUPABASE_URL}
        PUBLIC_SUPABASE_ANON_KEY: ${PUBLIC_SUPABASE_ANON_KEY}
    container_name: wireguard-config-manager
    ports:
      - "4321:4321"
    volumes:
      - ./env/.env:/app/.env:ro
    restart: unless-stopped
    env_file:
      - ./env/.env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    networks:
      - supabase_network_wireguard-config-manager

networks:
  supabase_network_wireguard-config-manager:
    external: true

